---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  serviceSubnet: "10.0.0.0/16"
  podSubnet: "10.244.0.0/16"
controlPlaneEndpoint: "{{ master_ip }}:6443"
apiServer:
  extraArgs:
    cloud-provider: "aws"
controllerManager:
  extraArgs:
    cloud-provider: "aws"
